openapi: 3.2.0
info:
  title: Decipher Rest Panel Datapoints API
  version: '1.0'
  description: The Decipher REST API allows comprehensive automation of your private or shared Decipher instance.
servers:
- url: https://{server}/api/v1
  description: Replace server with your instance domain.
  variables:
    server:
      default: selfserve.decipherinc.com
      description: Server domain
security:
- APIKey: []
tags:
- name: Panel Datapoints
paths:
  /panels/{panel_id}/datapoints:
    get:
      operationId: getPanelDatapoints
      summary: List panel datapoints
      description: Returns the datapoints belonging to the specified panel.
      tags:
      - Panel Datapoints
      parameters:
      - name: panel_id
        description: panel's numeric ID
        in: path
        required: true
        schema:
          type: string
      - name: instance
        description: the Kinesis Panel instance/host
        in: query
        required: true
        schema:
          type: string
      - name: survey
        description: a survey with the panel's API key in its path
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    choices:
                      type: array
                      items:
                        type: object
                        properties:
                          choice:
                            type: string
                            description: answer option text
                          export_value:
                            type: integer
                            description: the export value
                          value:
                            type: integer
                            description: unique (across entire panel) numeric ID
                    fingerprint:
                      type: string
                      description: 'hash of the datapoint, ignoring text and export value changes

                        '
                    group:
                      type: string
                      description: group to which the datapoint belongs
                    label:
                      type: string
                      description: 'the unique, alphanumeric identifier for this question

                        '
                    modified:
                      type: integer
                      description: the modification time of the datapoint
                    system_field:
                      type: string
                      description: system field referencing the datapoint
                    text:
                      type: string
                      description: the datapoint's question text or description
                    type:
                      type: string
                      description: the datapoint's question type
              example:
              - choices:
                - choice: Male
                  export_value: 10
                  value: 1
                - choice: Female
                  export_value: 11
                  value: 2
                - choice: Prefer not to say
                  export_value: 99
                  value: 247
                fingerprint: 42a637
                group: null
                label: Qgender
                modified: 1468518354
                system_field: gender
                text: Gender
                type: radio
              - choices: []
                fingerprint: c74d97
                group: null
                label: Qzip
                modified: 1459877107
                system_field: zip-postal_code
                text: What is your zip code?
                type: openend
    post:
      operationId: createPanelDatapoints
      summary: Push datapoints
      description: 'Create new datapoints on a Kinesis Panel from a Decipher survey''s

        questions.'
      tags:
      - Panel Datapoints
      parameters:
      - name: panel_id
        description: The panel's numeric ID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                instance:
                  description: The Kinesis Panel instance/host
                  type: string
                survey:
                  description: 'The survey containing the questions to create as panel datapoints

                    '
                  type: string
              required:
              - instance
              - survey
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  failed:
                    type: array
                    description: an array of errors for questions that failed
                    items:
                      type: object
                      properties:
                        error:
                          type: string
                          description: a description of the error
                        label:
                          type: string
                          description: label of the question that failed
                  successful:
                    type: array
                    description: an array of labels of questions that succeeded
                    items:
                      type: string
              example:
                failed:
                - error: Choices not allowed for type
                  label: q4
                successful:
                - q1
                - q2
                - q3
components:
  securitySchemes:
    APIKey:
      type: apiKey
      in: header
      name: x-apikey
      description: 'In order to access the api, you''ll need to generate an API key. Refer to the

        instructions [here](/docs/decipher/api#section/API-Keys) to generate and

        configure an API key with the appropriate permission sets. You can generate

        as many keys as required.


        Configure each request to include your API key in the request header. For example:


        ```

        x-apikey: dp48ss3mgsaucyjtybxw728h7s4cgnwzhejtszdwhf4xpe8yhmtdwpk2ntdhtwbs

        ```

        '
x-tagGroups:
- name: Autoclose
  tags:
  - Autoclose
- name: Data Input and Output
  tags:
  - Data
  - Data Feed
  - Response Summary
  - Modifying Data
  - Datasources
  - Datasources Data
  - Umerge
- name: Survey Metadata
  tags:
  - Simulated Data
  - Survey State
  - Survey Evaluate
  - Survey Quotas
  - Survey Files
  - Survey Warnings
  - Survey Terms
  - Survey Subscribers
  - Survey Users
  - Survey Tasks
- name: Panels
  tags:
  - Panel Data
  - Panel Datapoints
  - Survey Panels
- name: Research Hub
  tags:
  - Users
  - Companies
  - Categories
  - Surveys
  - Panels
  - Crosstabs
  - Archives
  - Archival Reports
  - API Keys
  - Usage
  - Warnings Summary
- name: Crosstabs
  tags:
  - Crosstabs Configuration
  - Crosstabs Execution
  - Crosstabs Nets
  - Saved Crosstabs
  - Crosstabs Table Settings
  - Crosstabs Validation
  - Crosstabs Rim Weighting
- name: Dashboards
  tags:
  - Dashboards
- name: DQ APIs
  tags:
  - DQ-Specific API Calls
  - MaxDiff API Calls
  - Discrete Choice Model API Calls
  - Media Testimonial API Calls
- name: Response Summary
  tags:
  - Share Link
- name: Sample Management
  tags:
  - Bounced Emails
  - Participant Sources
- name: Distribution
  tags:
  - Email Distribution
  - SFTP Distribution
  - Slack Distribution
- name: Campaign Manager
  tags:
  - Campaigns
  - Campaign Email Invites
  - Campaign Exports
  - Campaign Lists
  - Shared Campaign Lists
  - Campaign Sends
  - Campaign Status Lists
  - Supression Lists
- name: Question Library
  tags:
  - Company Element
  - Company Elements
  - Survey Elements
  - Survey Element Report Settings
- name: Language Manager
  tags:
  - LM Application Data
  - LM Application Translations
  - Translation Resources
  - Translations
  - Translation Deltas
  - Translation Reservations
  - Primary Survey Language
  - Other Survey Languages
  - Unused Survey Languages
- name: Project Parameters
  tags:
  - Available Project Parameters
  - Saved Project Parameters
  - Project Parameters Configuration
- name: Multi-User Editing
  tags:
  - Available Sections
  - Check Out Section
  - Check In Section
  - Sync Section
  - Section Editor
  - Abandon Section
  - Validate Section
- name: Video Management
  tags:
  - Videos
  - Watermarked Videos
- name: Miscellaneous
  tags:
  - System Information
  - Logic Nodes
  - Logic Events
  - CATI
  - Global Search
  - Miscellaneous
